version: 2.1
orbs:
  coveralls: coveralls/coveralls@2.1.0
jobs:
  build:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run:
          name: Install and Make
          command: npm install && npm test
      - coveralls/upload